//CCS_UNIQUE 818GLQUYE9J
// flow-typed signature: 733538cafe88d40242646b087fbb1435
// flow-typed version: <<STUB>>/namecase_v^1.1.2/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'namecase'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'namecase' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'namecase/meteor' {
  declare module.exports: any;
}

declare module 'namecase/namecase' {
  declare module.exports: any;
}

declare module 'namecase/package' {
  declare module.exports: any;
}

declare module 'namecase/test/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'namecase/meteor.js' {
  declare module.exports: $Exports<'namecase/meteor'>;
}
declare module 'namecase/namecase.js' {
  declare module.exports: $Exports<'namecase/namecase'>;
}
declare module 'namecase/package.js' {
  declare module.exports: $Exports<'namecase/package'>;
}
declare module 'namecase/test/tests.js' {
  declare module.exports: $Exports<'namecase/test/tests'>;
}
