//CCS_UNIQUE EIUSHU34WDR
// flow-typed signature: 1eef89ecaaa0e6a15615d71a75900f67
// flow-typed version: <<STUB>>/neo4j-driver_v^1.5.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'neo4j-driver'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'neo4j-driver' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'neo4j-driver/examples/node' {
  declare module.exports: any;
}

declare module 'neo4j-driver/gulpfile.babel' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/browser/neo4j-web' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/browser/neo4j-web.min' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/external/text-encoding/index' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/external/text-encoding/lib/encoding-indexes' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/external/text-encoding/lib/encoding' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/external/text-encoding/util/externs' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/index' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/driver' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/error' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/graph-types' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/index' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/integer' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/internal/bookmark' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/internal/buf' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/internal/ch-config' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/internal/ch-dummy' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/internal/ch-node' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/internal/ch-websocket' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/internal/chunking' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/internal/connection-holder' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/internal/connection-providers' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/internal/connectivity-verifier' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/internal/connector' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/internal/features' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/internal/host-name-resolvers' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/internal/least-connected-load-balancing-strategy' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/internal/load-balancing-strategy' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/internal/packstream' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/internal/pool-config' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/internal/pool' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/internal/rediscovery' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/internal/round-robin-array-index' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/internal/round-robin-load-balancing-strategy' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/internal/routing-table' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/internal/routing-util' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/internal/server-version' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/internal/stream-observer' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/internal/transaction-executor' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/internal/utf8' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/internal/util' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/record' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/result-summary' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/result' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/routing-driver' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/session' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/v1/transaction' {
  declare module.exports: any;
}

declare module 'neo4j-driver/lib/version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'neo4j-driver/examples/node.js' {
  declare module.exports: $Exports<'neo4j-driver/examples/node'>;
}
declare module 'neo4j-driver/gulpfile.babel.js' {
  declare module.exports: $Exports<'neo4j-driver/gulpfile.babel'>;
}
declare module 'neo4j-driver/lib/browser/neo4j-web.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/browser/neo4j-web'>;
}
declare module 'neo4j-driver/lib/browser/neo4j-web.min.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/browser/neo4j-web.min'>;
}
declare module 'neo4j-driver/lib/external/text-encoding/index.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/external/text-encoding/index'>;
}
declare module 'neo4j-driver/lib/external/text-encoding/lib/encoding-indexes.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/external/text-encoding/lib/encoding-indexes'>;
}
declare module 'neo4j-driver/lib/external/text-encoding/lib/encoding.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/external/text-encoding/lib/encoding'>;
}
declare module 'neo4j-driver/lib/external/text-encoding/util/externs.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/external/text-encoding/util/externs'>;
}
declare module 'neo4j-driver/lib/index.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/index'>;
}
declare module 'neo4j-driver/lib/v1/driver.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/driver'>;
}
declare module 'neo4j-driver/lib/v1/error.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/error'>;
}
declare module 'neo4j-driver/lib/v1/graph-types.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/graph-types'>;
}
declare module 'neo4j-driver/lib/v1/index.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/index'>;
}
declare module 'neo4j-driver/lib/v1/integer.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/integer'>;
}
declare module 'neo4j-driver/lib/v1/internal/bookmark.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/internal/bookmark'>;
}
declare module 'neo4j-driver/lib/v1/internal/buf.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/internal/buf'>;
}
declare module 'neo4j-driver/lib/v1/internal/ch-config.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/internal/ch-config'>;
}
declare module 'neo4j-driver/lib/v1/internal/ch-dummy.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/internal/ch-dummy'>;
}
declare module 'neo4j-driver/lib/v1/internal/ch-node.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/internal/ch-node'>;
}
declare module 'neo4j-driver/lib/v1/internal/ch-websocket.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/internal/ch-websocket'>;
}
declare module 'neo4j-driver/lib/v1/internal/chunking.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/internal/chunking'>;
}
declare module 'neo4j-driver/lib/v1/internal/connection-holder.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/internal/connection-holder'>;
}
declare module 'neo4j-driver/lib/v1/internal/connection-providers.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/internal/connection-providers'>;
}
declare module 'neo4j-driver/lib/v1/internal/connectivity-verifier.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/internal/connectivity-verifier'>;
}
declare module 'neo4j-driver/lib/v1/internal/connector.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/internal/connector'>;
}
declare module 'neo4j-driver/lib/v1/internal/features.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/internal/features'>;
}
declare module 'neo4j-driver/lib/v1/internal/host-name-resolvers.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/internal/host-name-resolvers'>;
}
declare module 'neo4j-driver/lib/v1/internal/least-connected-load-balancing-strategy.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/internal/least-connected-load-balancing-strategy'>;
}
declare module 'neo4j-driver/lib/v1/internal/load-balancing-strategy.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/internal/load-balancing-strategy'>;
}
declare module 'neo4j-driver/lib/v1/internal/packstream.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/internal/packstream'>;
}
declare module 'neo4j-driver/lib/v1/internal/pool-config.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/internal/pool-config'>;
}
declare module 'neo4j-driver/lib/v1/internal/pool.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/internal/pool'>;
}
declare module 'neo4j-driver/lib/v1/internal/rediscovery.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/internal/rediscovery'>;
}
declare module 'neo4j-driver/lib/v1/internal/round-robin-array-index.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/internal/round-robin-array-index'>;
}
declare module 'neo4j-driver/lib/v1/internal/round-robin-load-balancing-strategy.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/internal/round-robin-load-balancing-strategy'>;
}
declare module 'neo4j-driver/lib/v1/internal/routing-table.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/internal/routing-table'>;
}
declare module 'neo4j-driver/lib/v1/internal/routing-util.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/internal/routing-util'>;
}
declare module 'neo4j-driver/lib/v1/internal/server-version.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/internal/server-version'>;
}
declare module 'neo4j-driver/lib/v1/internal/stream-observer.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/internal/stream-observer'>;
}
declare module 'neo4j-driver/lib/v1/internal/transaction-executor.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/internal/transaction-executor'>;
}
declare module 'neo4j-driver/lib/v1/internal/utf8.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/internal/utf8'>;
}
declare module 'neo4j-driver/lib/v1/internal/util.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/internal/util'>;
}
declare module 'neo4j-driver/lib/v1/record.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/record'>;
}
declare module 'neo4j-driver/lib/v1/result-summary.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/result-summary'>;
}
declare module 'neo4j-driver/lib/v1/result.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/result'>;
}
declare module 'neo4j-driver/lib/v1/routing-driver.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/routing-driver'>;
}
declare module 'neo4j-driver/lib/v1/session.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/session'>;
}
declare module 'neo4j-driver/lib/v1/transaction.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/v1/transaction'>;
}
declare module 'neo4j-driver/lib/version.js' {
  declare module.exports: $Exports<'neo4j-driver/lib/version'>;
}
