//CCS_UNIQUE LUPJQXTILS
// flow-typed signature: 5e8db05c95de4f3fab2c8b501f525840
// flow-typed version: <<STUB>>/parse-full-name_v^1.2.3/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parse-full-name'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'parse-full-name' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'parse-full-name/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'parse-full-name/index' {
  declare module.exports: $Exports<'parse-full-name'>;
}
declare module 'parse-full-name/index.js' {
  declare module.exports: $Exports<'parse-full-name'>;
}
declare module 'parse-full-name/test/index.js' {
  declare module.exports: $Exports<'parse-full-name/test/index'>;
}
