//CCS_UNIQUE G7YDFH83R3J
// flow-typed signature: 58ccb8de9f9c00a41604623af94e3a17
// flow-typed version: <<STUB>>/seraph-model_v^0.10.1/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'seraph-model'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'seraph-model' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'seraph-model/lib/compose' {
  declare module.exports: any;
}

declare module 'seraph-model/lib/composition-relation-cypher-list' {
  declare module.exports: any;
}

declare module 'seraph-model/lib/get-id' {
  declare module.exports: any;
}

declare module 'seraph-model/lib/model' {
  declare module.exports: any;
}

declare module 'seraph-model/lib/read' {
  declare module.exports: any;
}

declare module 'seraph-model/lib/schema' {
  declare module.exports: any;
}

declare module 'seraph-model/lib/sort-compositions' {
  declare module.exports: any;
}

declare module 'seraph-model/lib/transform-composed-nodes' {
  declare module.exports: any;
}

declare module 'seraph-model/lib/write' {
  declare module.exports: any;
}

declare module 'seraph-model/migrations/0.5-to-0.6' {
  declare module.exports: any;
}

declare module 'seraph-model/test/model_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'seraph-model/lib/compose.js' {
  declare module.exports: $Exports<'seraph-model/lib/compose'>;
}
declare module 'seraph-model/lib/composition-relation-cypher-list.js' {
  declare module.exports: $Exports<'seraph-model/lib/composition-relation-cypher-list'>;
}
declare module 'seraph-model/lib/get-id.js' {
  declare module.exports: $Exports<'seraph-model/lib/get-id'>;
}
declare module 'seraph-model/lib/model.js' {
  declare module.exports: $Exports<'seraph-model/lib/model'>;
}
declare module 'seraph-model/lib/read.js' {
  declare module.exports: $Exports<'seraph-model/lib/read'>;
}
declare module 'seraph-model/lib/schema.js' {
  declare module.exports: $Exports<'seraph-model/lib/schema'>;
}
declare module 'seraph-model/lib/sort-compositions.js' {
  declare module.exports: $Exports<'seraph-model/lib/sort-compositions'>;
}
declare module 'seraph-model/lib/transform-composed-nodes.js' {
  declare module.exports: $Exports<'seraph-model/lib/transform-composed-nodes'>;
}
declare module 'seraph-model/lib/write.js' {
  declare module.exports: $Exports<'seraph-model/lib/write'>;
}
declare module 'seraph-model/migrations/0.5-to-0.6.js' {
  declare module.exports: $Exports<'seraph-model/migrations/0.5-to-0.6'>;
}
declare module 'seraph-model/test/model_test.js' {
  declare module.exports: $Exports<'seraph-model/test/model_test'>;
}
