//CCS_UNIQUE KIHPTGWQIFL
// flow-typed signature: 0e670f313c72c3249e751e1dc97aa2e9
// flow-typed version: <<STUB>>/seraph_v^0.15.2/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'seraph'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'seraph' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'seraph/bolt' {
  declare module.exports: any;
}

declare module 'seraph/co' {
  declare module.exports: any;
}

declare module 'seraph/lib/bolt/seraph' {
  declare module.exports: any;
}

declare module 'seraph/lib/constraints' {
  declare module.exports: any;
}

declare module 'seraph/lib/index' {
  declare module.exports: any;
}

declare module 'seraph/lib/legacyindex' {
  declare module.exports: any;
}

declare module 'seraph/lib/node' {
  declare module.exports: any;
}

declare module 'seraph/lib/relationship' {
  declare module.exports: any;
}

declare module 'seraph/lib/seraph' {
  declare module.exports: any;
}

declare module 'seraph/test/batching' {
  declare module.exports: any;
}

declare module 'seraph/test/constraints' {
  declare module.exports: any;
}

declare module 'seraph/test/errors' {
  declare module.exports: any;
}

declare module 'seraph/test/index' {
  declare module.exports: any;
}

declare module 'seraph/test/label' {
  declare module.exports: any;
}

declare module 'seraph/test/legacy' {
  declare module.exports: any;
}

declare module 'seraph/test/legacyindex' {
  declare module.exports: any;
}

declare module 'seraph/test/node' {
  declare module.exports: any;
}

declare module 'seraph/test/query' {
  declare module.exports: any;
}

declare module 'seraph/test/relationship' {
  declare module.exports: any;
}

declare module 'seraph/test/root' {
  declare module.exports: any;
}

declare module 'seraph/test/seraph' {
  declare module.exports: any;
}

declare module 'seraph/test/util/database' {
  declare module.exports: any;
}

declare module 'seraph/test/util/ponies' {
  declare module.exports: any;
}

// Filename aliases
declare module 'seraph/bolt.js' {
  declare module.exports: $Exports<'seraph/bolt'>;
}
declare module 'seraph/co.js' {
  declare module.exports: $Exports<'seraph/co'>;
}
declare module 'seraph/lib/bolt/seraph.js' {
  declare module.exports: $Exports<'seraph/lib/bolt/seraph'>;
}
declare module 'seraph/lib/constraints.js' {
  declare module.exports: $Exports<'seraph/lib/constraints'>;
}
declare module 'seraph/lib/index.js' {
  declare module.exports: $Exports<'seraph/lib/index'>;
}
declare module 'seraph/lib/legacyindex.js' {
  declare module.exports: $Exports<'seraph/lib/legacyindex'>;
}
declare module 'seraph/lib/node.js' {
  declare module.exports: $Exports<'seraph/lib/node'>;
}
declare module 'seraph/lib/relationship.js' {
  declare module.exports: $Exports<'seraph/lib/relationship'>;
}
declare module 'seraph/lib/seraph.js' {
  declare module.exports: $Exports<'seraph/lib/seraph'>;
}
declare module 'seraph/test/batching.js' {
  declare module.exports: $Exports<'seraph/test/batching'>;
}
declare module 'seraph/test/constraints.js' {
  declare module.exports: $Exports<'seraph/test/constraints'>;
}
declare module 'seraph/test/errors.js' {
  declare module.exports: $Exports<'seraph/test/errors'>;
}
declare module 'seraph/test/index.js' {
  declare module.exports: $Exports<'seraph/test/index'>;
}
declare module 'seraph/test/label.js' {
  declare module.exports: $Exports<'seraph/test/label'>;
}
declare module 'seraph/test/legacy.js' {
  declare module.exports: $Exports<'seraph/test/legacy'>;
}
declare module 'seraph/test/legacyindex.js' {
  declare module.exports: $Exports<'seraph/test/legacyindex'>;
}
declare module 'seraph/test/node.js' {
  declare module.exports: $Exports<'seraph/test/node'>;
}
declare module 'seraph/test/query.js' {
  declare module.exports: $Exports<'seraph/test/query'>;
}
declare module 'seraph/test/relationship.js' {
  declare module.exports: $Exports<'seraph/test/relationship'>;
}
declare module 'seraph/test/root.js' {
  declare module.exports: $Exports<'seraph/test/root'>;
}
declare module 'seraph/test/seraph.js' {
  declare module.exports: $Exports<'seraph/test/seraph'>;
}
declare module 'seraph/test/util/database.js' {
  declare module.exports: $Exports<'seraph/test/util/database'>;
}
declare module 'seraph/test/util/ponies.js' {
  declare module.exports: $Exports<'seraph/test/util/ponies'>;
}
