//CCS_UNIQUE 88O4IYKP1AR
// flow-typed signature: b7f94c7122e10daa176269128b819284
// flow-typed version: <<STUB>>/shorthash_v^0.0.2/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shorthash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'shorthash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'shorthash/examples/sandbox' {
  declare module.exports: any;
}

declare module 'shorthash/shorthash' {
  declare module.exports: any;
}

// Filename aliases
declare module 'shorthash/examples/sandbox.js' {
  declare module.exports: $Exports<'shorthash/examples/sandbox'>;
}
declare module 'shorthash/index' {
  declare module.exports: $Exports<'shorthash'>;
}
declare module 'shorthash/index.js' {
  declare module.exports: $Exports<'shorthash'>;
}
declare module 'shorthash/shorthash.js' {
  declare module.exports: $Exports<'shorthash/shorthash'>;
}
