//CCS_UNIQUE RHGZ8FOO0MF
// flow-typed signature: d536e7c4188dda5deecbfa1299b98747
// flow-typed version: <<STUB>>/xxhashjs_v^0.2.1/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xxhashjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xxhashjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xxhashjs/benchmark/bench' {
  declare module.exports: any;
}

declare module 'xxhashjs/build/xxhash' {
  declare module.exports: any;
}

declare module 'xxhashjs/build/xxhash.min' {
  declare module.exports: any;
}

declare module 'xxhashjs/examples/from_file' {
  declare module.exports: any;
}

declare module 'xxhashjs/examples/from_file64' {
  declare module.exports: any;
}

declare module 'xxhashjs/examples/one_step' {
  declare module.exports: any;
}

declare module 'xxhashjs/lib/index' {
  declare module.exports: any;
}

declare module 'xxhashjs/lib/xxhash' {
  declare module.exports: any;
}

declare module 'xxhashjs/lib/xxhash64' {
  declare module.exports: any;
}

declare module 'xxhashjs/test/XXH-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'xxhashjs/benchmark/bench.js' {
  declare module.exports: $Exports<'xxhashjs/benchmark/bench'>;
}
declare module 'xxhashjs/build/xxhash.js' {
  declare module.exports: $Exports<'xxhashjs/build/xxhash'>;
}
declare module 'xxhashjs/build/xxhash.min.js' {
  declare module.exports: $Exports<'xxhashjs/build/xxhash.min'>;
}
declare module 'xxhashjs/examples/from_file.js' {
  declare module.exports: $Exports<'xxhashjs/examples/from_file'>;
}
declare module 'xxhashjs/examples/from_file64.js' {
  declare module.exports: $Exports<'xxhashjs/examples/from_file64'>;
}
declare module 'xxhashjs/examples/one_step.js' {
  declare module.exports: $Exports<'xxhashjs/examples/one_step'>;
}
declare module 'xxhashjs/lib/index.js' {
  declare module.exports: $Exports<'xxhashjs/lib/index'>;
}
declare module 'xxhashjs/lib/xxhash.js' {
  declare module.exports: $Exports<'xxhashjs/lib/xxhash'>;
}
declare module 'xxhashjs/lib/xxhash64.js' {
  declare module.exports: $Exports<'xxhashjs/lib/xxhash64'>;
}
declare module 'xxhashjs/test/XXH-test.js' {
  declare module.exports: $Exports<'xxhashjs/test/XXH-test'>;
}
